name: membership
version: 0.0.1
apiVersion: v1
description: membership microservice service
icon: https://www.jhipster.tech/images/logo/logo-jhipster-drink-coffee.svg
keywords:
- spring
- angular
- react
- JHipster
- membership
home: https://www.jhipster.tech/
sources:
- https://github.com/jhipster/generator-jhipster.git
maintainers:
- name: Team JHipster
  email:
